### ISSUE TITLE
ArgumentError on activerecord 7.0 with MySQL adapter

### ISSUE THREAD

**Issue by r7kamura** [cookpad/arproxy#20]
Since activerecord 7.0.0, `#execute` method might take keyword arguments in MySQL adapter, like `execute(sql, name, async: false)`.

This change was added at https://github.com/rails/rails/pull/40037.

**Comment by osyoyu** [comment]
database_rewinder's solution:

```rb
if meth.parameters.any? {|type, _name| [:key, :keyreq, :keyrest].include? type }
  mod.send :prepend, Execute::WithKwargs
else
  mod.send :prepend, Execute::NoKwargs
end
```

https://github.com/amatsuda/database_rewinder/blob/1d9b2f2d06c4e2137d3dabd9ef424a09f66fcd69/lib/database_rewinder/active_record_monkey.rb#L40-L44

**Comment by r7kamura** [comment]
I agree with using `Method#parameters` to check if keyword arguments are needed, but maybe we don't need to check it and just pass it through with `def execute(sql, name = nil, **)`, ...what do you think?

**Comment by r7kamura** [comment]
OK, I've created https://github.com/cookpad/arproxy/pull/21. Let's talk about the details there.
