### ISSUE TITLE
複数DB接続時にエラー？

### ISSUE THREAD

**Issue by takundao71** [cookpad/arproxy#4]
mysql2でAとBのdatabaseに接続しており、Bでクエリーを発行すると
何故かarproxy内でAに対してクエリーが発行されエラーになりました。

間違ってたらスイマセン

**Comment by mirakui** [comment]
こちらで再現できるように詳細を教えてもらえますか？
私は switch_point を使った MySQL の複数 DB 環境で arproxy を運用していますが、そのような状況はまだ見たことがありません。

**Comment by takundao71** [comment]
switch_pointは使用してないです。establish_connectionで複数DBに接続したら、arproxyでエラーになりました

**Comment by takundao71** [comment]
申し訳ありません。こちらconfig/initializers/ar_proxy.rb で ActiveRecord::Baseを使っており、デフォルトの設定でsqlを発行していたことが問題でした。お騒がせしました。

**Comment by mirakui** [comment]
なるほど、了解です！ close します〜
